<div id="comments" class="comments-area" <?php tc_echo('element_attributes') ?>>
  <?php do_action('tc_before_comments_template') ?>
  <?php
/* We kinda need to do this this way as the WP_Comment_Query is generated by the function below */
  comments_template( '' , true ) ?>
  <?php do_action('tc_after_comments_template') ?>
</div>
